# Generated by Django 6.0.2 on 2026-02-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='job',
            name='reliefweb_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
