# Generated by Django 6.0.2 on 2026-02-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_created_at_alter_job_reliefweb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='career_categories',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
