# Generated by Django 6.0.2 on 2026-02-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_career_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
